version: "3.8"

services:
  dayz:
    image: ghcr.io/zahornyak/dayz-server-manager:master
    ports:
      - "2302-2312:2302-2312"
      - "8766:8766"
      - "27016:27016"
      - "80:8080" # publish the web server on port 8080 in your config
    volumes:
      - "./:/dayz" # make sure your server-manager.json is in there
    tty: true # needed for inputs
